# Generated by Django 3.2.18 on 2023-05-14 17:36

from django.db import migrations


INITIAL_TAGS = [
    {'color': '#49B64E', 'name': 'Завтрак', 'slug': 'breakfast'},
    {'color': '#E26C2D', 'name': 'Обед', 'slug': 'dinner'},
    {'color': '#8775D2', 'name': 'Ужин', 'slug': 'supper'}
]


def add_tags(apps, schema_editor):
    Tag = apps.get_model('recipes', 'Tag')
    for tag in INITIAL_TAGS:
        new_tag = Tag(**tag)
        new_tag.save()


def remove_tags(apps, schema_editor):
    Tag = apps.get_model('recipes', 'Tag')
    for tag in INITIAL_TAGS:
        Tag.objects.get(name=tag['name']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.RunPython(add_tags, remove_tags)
    ]
