# Generated by Django 3.2.18 on 2023-05-14 17:40

import json

from django.db import migrations

with open('./data/ingredients.json', 'r', encoding="utf-8") as file:
    INITIAL_INGREDIENTS = json.loads(file.read())


def add_ingredients(apps, schema_editor):

    Ingredient = apps.get_model('recipes', 'Ingredient')
    for ingredient in INITIAL_INGREDIENTS:
        new_ingredient = Ingredient(**ingredient)
        new_ingredient.save()


def remove_ingredients(apps, schema_editor):
    Ingredient = apps.get_model('recipes', 'Ingredient')
    for ingredient in INITIAL_INGREDIENTS:
        Ingredient.objects.get(name=ingredient['name']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_add_tags'),
    ]

    operations = [
        migrations.RunPython(add_ingredients, remove_ingredients)
    ]
